### ISSUE TITLE
About the requirements of this repo.

### ISSUE THREAD

**Issue by zezhishao** [fecet/NBeats-M4#1]
Hi, many thanks for you contribution!
I'm trying to reproduce NBeats on the M4 dataset, and this repo helped me alot.
I was wondering if you could provide a `requirements.txt` for me to install required packages?
The most important thing is the Tensorflow version, because the compatibility between different versions of Tensorflow is too poor.

**Comment by fecet** [comment]
Hello, I think this mainly depended on https://github.com/philipperemy/n-beats, you can check requirements there. As for version of tf, I cant really remember exactlty but it should be the latest stable version at that time, probably 2.13-2.15.

**Comment by zezhishao** [comment]
Thanks for your quick reply, it solved my problem!
